# Generated by Django 5.0.3 on 2024-04-04 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_messages_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='message',
            new_name='description',
        ),
    ]
